name: 'WordPress Plugin Deploy'
description: 'Deploy to the WordPress Plugin Repository'
author: 'nextgenthemes' # inspired by 10up action

inputs:
  svn_user:
    required: false
  svn_pass:
    required: false
  version:
    description: Is required unless you just update readme and assets
    required: false
  workdir:
    description: Optional relative path to where the main plugin file is.
    required: false
  build_dirs:
    description: Comma seperated list of folders to include in distribution.
    required: false
  args:
    description: Use --readme-only and/or --dry-run 
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}

branding:
  icon: 'upload-cloud'
  color: 'blue'
