<?php
array(
	'https://alugha.com/videos/e269333a-579b-11e5-aa10-8587cc892389/share' => false,
	'https://alugha.com/1/videos/youtube-54m1YfEuYU8'  => false,
	'https://alugha.com/videos/7cab9cd7-f64a-11e5-939b-c39074d29b86' => false,
	'https://archive.org/details/arashyekt4_gmail_Cat' => false,
	'https://banned.video/watch?id=5ffe509f0d763c3dca0e8ad7' => false,
	'https://www.bitchute.com/video/eCctkmPpK8tq/'     => false,
	'https://www.break.com/video/first-person-pov-of-tornado-strike-2542591-test' => false,
	'http://view.break.com/2542591-test'               => false,
	'http://www.break.com/embed/2542591?embed=1'       => false,
	'https://players.brightcove.net/624246174001/BJXA5Px6f_default/index.html?videoId=5809251338001' => false,
	'http://players.brightcove.net/1160438696001/default_default/index.html?videoId=4587535845001' => false,
	'http://players.brightcove.net/5107476400001/B1xUkhW8i_default/index.html?videoId=5371391223001' => false,
	'https://cantcensortruth.com/watch?id=601218b0de226411596203ae' => false,
	'http://media.mtvnservices.com/embed/mgid:arc:video:comedycentral.com:c80adf02-3e24-437a-8087-d6b77060571c' => false,
	'http://media.mtvnservices.com/embed/mgid:arc:video:comedycentral.com:c3c1da76-96c2-48b4-b38d-8bb16fbf7a58' => false,
	'https://www.dailymotion.com/video/x41ia79_mass-effect-andromeda-gameplay-alpha_videogames' =>
	(object) array(
		'type'             => 'video',
		'version'          => '1.0',
		'provider_name'    => 'Dailymotion',
		'provider_url'     => 'https://www.dailymotion.com',
		'title'            => 'Mass Effect Andromeda - Gameplay Alpha',
		'description'      => 'Mass Effect Andromeda - Gameplay Alpha',
		'author_name'      => 'HobbyConsolas',
		'author_url'       => 'https://www.dailymotion.com/hobbyconsolas',
		'width'            => 500,
		'height'           => 281,
		'html'             => '<iframe frameborder="0" width="500" height="281" src="https://www.dailymotion.com/embed/video/x41ia79" allowfullscreen allow="autoplay"></iframe>',
		'thumbnail_url'    => 'https://s2.dmcdn.net/v/EaJKb1VtG7bVmBvu0/x240',
		'thumbnail_width'  => 427,
		'thumbnail_height' => 240,
	),
	'https://dai.ly/x3cwlqz'                           =>
	(object) array(
		'type'             => 'video',
		'version'          => '1.0',
		'provider_name'    => 'Dailymotion',
		'provider_url'     => 'https://www.dailymotion.com',
		'title'            => 'Mass Effect Andromeda',
		'description'      => '&nbsp; Ayer fue 7 de Noviembre y qué mejor manera de c',
		'author_name'      => 'meristation',
		'author_url'       => 'https://www.dailymotion.com/meristation',
		'width'            => 500,
		'height'           => 281,
		'html'             => '<iframe frameborder="0" width="500" height="281" src="https://www.dailymotion.com/embed/video/x3cwlqz" allowfullscreen allow="autoplay"></iframe>',
		'thumbnail_url'    => 'https://s2.dmcdn.net/v/C6guR1VtGCKc0mNPC/x240',
		'thumbnail_width'  => 484,
		'thumbnail_height' => 240,
	),
	'http://www.dailymotion.com/playlist/x3yk8p_PHIL-MDS_nature-et-environnement-2011/1#video=xm3x45' => false,
	'https://d.tube/#!/v/exyle/bgc244pb'               => false,
	'https://www.facebook.com/TheKillingsOfTonyBlair/videos/vb.551089058285349/562955837098671/?type=2&theater' => false,
	'https://web.facebook.com/XTvideo/videos/10153906059711871/' => false,
	'http://www.funnyordie.com/videos/76585438d8/sarah-silverman-s-we-are-miracles-hbo-special' => false,
	'https://drive.google.com/file/d/0BymXD1aD6QzJWkh4Q0hPRWlPYkk/edit' => null,
	'https://example.com/'                             => false,
	'https://www.ign.com/videos/2012/03/06/mass-effect-3-video-review' => null,
	'https://www.kickstarter.com/projects/obsidian/project-eternity?ref=discovery' => false,
	'https://www.kickstarter.com/projects/trinandtonic/friendship-postcards?ref=category_featured' => false,
	'http://www.klagemauer.tv/9106'                    => false,
	'http://www.kla.tv/9122'                           => false,
	'http://www.liveleak.com/view?i=703_1385224413'    => false,
	'http://www.liveleak.com/view?f=c85bdf5e45b2'      => false,
	'https://www.liveleak.com/view?t=uGBX9_1579730411' => false,
	'https://livestream.com/accounts/23470201/events/7021166' => false,
	'https://livestream.com/accounts/467901/events/2015991/videos/17500857/player?width=640&height=360&enableInfo=true&defaultDrawer=&autoPlay=true&mute=false' => false,
	'http://www.metacafe.com/watch/11433151/magical-handheld-fireballs/' => false,
	'http://www.metacafe.com/watch/11322264/everything_wrong_with_robocop_in_7_minutes/' => false,
	'https://myspace.com/myspace/video/dark-rooms-the-shadow-that-looms-o-er-my-heart-live-/109471212' => null,
	'https://rumble.com/vd6thp-gigantic-galapagos-tortoise-casually-strolls-through-a-restaurant.html' => false,
	'https://rumble.com/embed/vd6thp/?foo=bar'         => false,
	'https://rutube.ru/play/embed/9822149'             => false,
	'https://www.snotr.com/video/12314/How_big_a_truck_blind_spot_really_is' => false,
	'http://media.mtvnservices.com/embed/mgid:arc:video:spike.com:6a219882-c412-46ce-a8c9-32e043396621' => false,
	'https://www.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it' =>
	(object) array(
		'type'             => 'video',
		'version'          => '1.0',
		'width'            => 500,
		'height'           => 282,
		'title'            => 'Sam Harris: Can we build AI without losing control over it?',
		'description'      => 'Scared of superintelligent AI? You should be, says neur',
		'url'              => 'https://www.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it',
		'author_name'      => 'Sam Harris',
		'provider_name'    => 'TED',
		'provider_url'     => 'https://www.ted.com',
		'cache_age'        => 300,
		'thumbnail_url'    => 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/51c9b741-275c-4ea0-bb9d-11b9aa8d1165/SamHarris_2016T-embed.jpg?h=282&w=500',
		'thumbnail_width'  => 500,
		'thumbnail_height' => 282,
		'author_url'       => 'https://www.ted.com/speakers/sam_harris',
		'html'             => '<iframe src="https://embed.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it" width="500" height="282" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>',
	),
	'https://www.twitch.tv/whiskeyexperts'             => false,
	'https://www.twitch.tv/imaqtpie'                   => false,
	'https://www.twitch.tv/imaqtpie/v/95318019'        => false,
	'http://www.ustream.tv/recorded/59999872?utm_campaign=ustre.am&utm_source=ustre.am/:43KHS&utm_medium=social&utm_content=20170405204127' => false,
	'http://www.ustream.tv/embed/17074538?wmode=transparent&v=3&autoplay=false' => false,
	'https://www.viddler.com/v/a695c468'               => false,
	'https://vimeo.com/124400795'                      =>
	(object) array(
		'type'                           => 'video',
		'version'                        => '1.0',
		'provider_name'                  => 'Vimeo',
		'provider_url'                   => 'https://vimeo.com/',
		'title'                          => 'One Bright Dot',
		'author_name'                    => 'Clément Morin',
		'author_url'                     => 'https://vimeo.com/clementmorin',
		'is_plus'                        => '1',
		'account_type'                   => 'plus',
		'html'                           => '<iframe src="https://player.vimeo.com/video/124400795?dnt=1&amp;app_id=122963" width="500" height="281" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="One Bright Dot"></iframe>',
		'width'                          => 500,
		'height'                         => 281,
		'duration'                       => 119,
		'description'                    => 'A little light rises from the deep sea.

Pictures : Cl�',
		'thumbnail_url'                  => 'https://i.vimeocdn.com/video/514111591_295x166.jpg',
		'thumbnail_width'                => 295,
		'thumbnail_height'               => 166,
		'thumbnail_url_with_play_button' => 'https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F514111591_295x166.jpg&src1=http%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png',
		'upload_date'                    => '2015-04-08 07:04:07',
		'video_id'                       => 124400795,
		'uri'                            => '/videos/124400795',
	),
	'https://player.vimeo.com/124400795'               =>
	(object) array(
		'type'                           => 'video',
		'version'                        => '1.0',
		'provider_name'                  => 'Vimeo',
		'provider_url'                   => 'https://vimeo.com/',
		'title'                          => 'One Bright Dot',
		'author_name'                    => 'Clément Morin',
		'author_url'                     => 'https://vimeo.com/clementmorin',
		'is_plus'                        => '1',
		'account_type'                   => 'plus',
		'html'                           => '<iframe src="https://player.vimeo.com/video/124400795?dnt=1&amp;app_id=122963" width="500" height="281" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="One Bright Dot"></iframe>',
		'width'                          => 500,
		'height'                         => 281,
		'duration'                       => 119,
		'description'                    => 'A little light rises from the deep sea.

Pictures : Cl�',
		'thumbnail_url'                  => 'https://i.vimeocdn.com/video/514111591_295x166.jpg',
		'thumbnail_width'                => 295,
		'thumbnail_height'               => 166,
		'thumbnail_url_with_play_button' => 'https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F514111591_295x166.jpg&src1=http%3A%2F%2Ff.vimeocdn.com%2Fp%2Fimages%2Fcrawler_play.png',
		'upload_date'                    => '2015-04-08 07:04:07',
		'video_id'                       => 124400795,
		'uri'                            => '/videos/124400795',
	),
	'https://vk.com/video_ext.php?oid=162756656&id=171388096&hash=b82cc24232fe7f9f&hd=1' => false,
	'https://vzaar.com/videos/993324'                  => false,
	'https://vzaar.com/videos/1515906'                 => false,
	'https://fast.wistia.net/embed/iframe/g5pnf59ala'  =>
	(object) array(
		'version'          => '1.0',
		'type'             => 'video',
		'html'             => '<iframe src="https://fast.wistia.net/embed/iframe/g5pnf59ala?dnt=1" title="Dan Mills - Young and Free Video" allow="autoplay; fullscreen" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen msallowfullscreen width="500" height="281"></iframe>
<script src="https://fast.wistia.net/assets/external/E-v1.js" async></script>',
		'width'            => 500,
		'height'           => 281,
		'provider_name'    => 'Wistia, Inc.',
		'provider_url'     => 'https://wistia.com',
		'title'            => 'Dan Mills - Young and Free',
		'thumbnail_url'    => 'https://embed-ssl.wistia.com/deliveries/963ecb7ea4e5483d1568d0b526e2cf4cbffa5e5a.jpg?image_crop_resized=500x281',
		'thumbnail_width'  => 500,
		'thumbnail_height' => 281,
		'player_color'     => '1039e0',
		'duration'         => 205.0,
	),
	'https://how-2-drive.wistia.com/medias/fi1rqe3kiy' =>
	(object) array(
		'version'          => '1.0',
		'type'             => 'video',
		'html'             => '<iframe src="https://fast.wistia.net/embed/iframe/fi1rqe3kiy?dnt=1" title="Driving Lessons in Norfolk &amp; Suffolk Video" allow="autoplay; fullscreen" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen msallowfullscreen width="500" height="281"></iframe>
<script src="https://fast.wistia.net/assets/external/E-v1.js" async></script>',
		'width'            => 500,
		'height'           => 281,
		'provider_name'    => 'Wistia, Inc.',
		'provider_url'     => 'https://wistia.com',
		'title'            => 'Driving Lessons in Norfolk &amp; Suffolk',
		'thumbnail_url'    => 'https://embed-ssl.wistia.com/deliveries/2557976b62c935b8d82bf7da7ea611213cc6fbca.jpg?image_crop_resized=500x281',
		'thumbnail_width'  => 500,
		'thumbnail_height' => 281,
		'player_color'     => 'ea1b22',
		'duration'         => 87.727,
	),
	'http://www.xtube.com/watch.php?v=1234'            => false,
	'https://de.sports.yahoo.com/video/krasse-vorher-nachher-bilder-mann-094957265.html?format=embed&player_autoplay=false' => false,
	'https://www.yahoo.com/movies/sully-trailer-4-211012511.html?format=embed' => false,
	'http://v.youku.com/v_show/id_XMTczMDAxMjIyNA==.html?f=27806190' => false,
	'http://player.youku.com/embed/XMTUyODYwOTc4OA=='  => false,
	'https://www.youtube.com/watch?v=-fEo3kgHFaw'      =>
	(object) array(
		'title'            => 'The Voice of Germany – I want you Trailer',
		'author_name'      => 'HQGamingNetwork',
		'author_url'       => 'https://www.youtube.com/c/HQGamingNetwork',
		'type'             => 'video',
		'height'           => 281,
		'width'            => 500,
		'version'          => '1.0',
		'provider_name'    => 'YouTube',
		'provider_url'     => 'https://www.youtube.com/',
		'thumbnail_height' => 360,
		'thumbnail_width'  => 480,
		'thumbnail_url'    => 'https://i.ytimg.com/vi/-fEo3kgHFaw/hqdefault.jpg',
		'html'             => '<iframe width="500" height="281" src="https://www.youtube.com/embed/-fEo3kgHFaw?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
	),
	'https://www.youtube.com/watch?time_continue=1&v=eqnnyDa7C7Q&feature=emb_logo' =>
	(object) array(
		'title'            => 'Broward County Administrator Discussing Removing People From Family Homes for COVID-19 Quarantines',
		'author_name'      => 'National File',
		'author_url'       => 'https://www.youtube.com/channel/UC3eiU1hikmzLkJgXDNtN7AQ',
		'type'             => 'video',
		'height'           => 281,
		'width'            => 500,
		'version'          => '1.0',
		'provider_name'    => 'YouTube',
		'provider_url'     => 'https://www.youtube.com/',
		'thumbnail_height' => 360,
		'thumbnail_width'  => 480,
		'thumbnail_url'    => 'https://i.ytimg.com/vi/eqnnyDa7C7Q/hqdefault.jpg',
		'html'             => '<iframe width="500" height="281" src="https://www.youtube.com/embed/eqnnyDa7C7Q?start=1&feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
	),
	'https://youtu.be/hRonZ4wP8Ys'                     =>
	(object) array(
		'title'            => 'One Bright Dot',
		'author_name'      => 'Maxon VFX',
		'author_url'       => 'https://www.youtube.com/user/MaxonC4D',
		'type'             => 'video',
		'height'           => 281,
		'width'            => 500,
		'version'          => '1.0',
		'provider_name'    => 'YouTube',
		'provider_url'     => 'https://www.youtube.com/',
		'thumbnail_height' => 360,
		'thumbnail_width'  => 480,
		'thumbnail_url'    => 'https://i.ytimg.com/vi/hRonZ4wP8Ys/hqdefault.jpg',
		'html'             => '<iframe width="500" height="281" src="https://www.youtube.com/embed/hRonZ4wP8Ys?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
	),
	'http://www.youtube.com/watch?v=GjL82KUHVb0&list=PLI46g-I12_9qGBq-4epxOay0hotjys5iA&index=10' =>
	(object) array(
		'title'            => '[191] Conspiracy to Commit Journalism, Nestlé Corporate Trolls, Supreme Court Historic Rulings',
		'author_name'      => 'breakingtheset',
		'author_url'       => 'https://www.youtube.com/user/breakingtheset',
		'type'             => 'video',
		'height'           => 281,
		'width'            => 500,
		'version'          => '1.0',
		'provider_name'    => 'YouTube',
		'provider_url'     => 'https://www.youtube.com/',
		'thumbnail_height' => 360,
		'thumbnail_width'  => 480,
		'thumbnail_url'    => 'https://i.ytimg.com/vi/GjL82KUHVb0/hqdefault.jpg',
		'html'             => '<iframe width="500" height="281" src="https://www.youtube.com/embed/GjL82KUHVb0?list=PLI46g-I12_9qGBq-4epxOay0hotjys5iA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
	),
	'https://youtu.be/b8m9zhNAgKs?list=PLI_7Mg2Z_-4I-W_lI55D9lBUkC66ftHMg' =>
	(object) array(
		'title'            => 'Rae Sremmurd - Black Beatles ft. Gucci Mane (Official Video)',
		'author_name'      => 'RaeSremmurdVEVO',
		'author_url'       => 'https://www.youtube.com/user/RaeSremmurdVEVO',
		'type'             => 'video',
		'height'           => 281,
		'width'            => 500,
		'version'          => '1.0',
		'provider_name'    => 'YouTube',
		'provider_url'     => 'https://www.youtube.com/',
		'thumbnail_height' => 360,
		'thumbnail_width'  => 480,
		'thumbnail_url'    => 'https://i.ytimg.com/vi/b8m9zhNAgKs/hqdefault.jpg',
		'html'             => '<iframe width="500" height="281" src="https://www.youtube.com/embed/b8m9zhNAgKs?list=PLI_7Mg2Z_-4I-W_lI55D9lBUkC66ftHMg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
	),
	'https://www.youtube.com/playlist?list=PL3Esg-ZzbiUmeSKBAQ3ej1hQxDSsmnp-7' =>
	(object) array(
		'title'            => '#BarCode',
		'author_name'      => 'NuoViso.TV',
		'author_url'       => '/c/NuovisoTvFilmproduktion',
		'type'             => 'video',
		'height'           => 281,
		'width'            => 500,
		'version'          => '1.0',
		'provider_name'    => 'YouTube',
		'provider_url'     => 'https://www.youtube.com/',
		'thumbnail_height' => 360,
		'thumbnail_width'  => 480,
		'thumbnail_url'    => 'https://i.ytimg.com/vi/Z1JCY9UMaXU/hqdefault.jpg',
		'html'             => '<iframe width="500" height="281" src="https://www.youtube.com/embed/videoseries?list=PL3Esg-ZzbiUmeSKBAQ3ej1hQxDSsmnp-7" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
	),
	'https://www.youtube.com/embed/videoseries?list=PLMUvgtCRyn-6obmhiDS4n5vYQN3bJRduk' => false,
);
