<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit516b5fd3c4d56c19317857df7012b08f {

	public static $files = array(
		'c14057a02afc95b84dc5bf85d98c5b66' => __DIR__ . '/..' . '/julien731/wp-dismissible-notices-handler/handler.php',
		'ff8834a662873e3e689a4283b27598d2' => __DIR__ . '/..' . '/julien731/wp-dismissible-notices-handler/includes/helper-functions.php',
	);

	public static function getInitializer( ClassLoader $loader ) {
		return \Closure::bind(
			function () use ( $loader ) {

			},
			null,
			ClassLoader::class
		);
	}
}
