# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    default_labels:
      - "dependencies"
    version_requirement_updates: "increase_versions"
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "monthly"
    default_labels:
      - "dependencies"
    version_requirement_updates: "increase_versions
