<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'c14057a02afc95b84dc5bf85d98c5b66' => $vendorDir . '/julien731/wp-dismissible-notices-handler/handler.php',
    'ff8834a662873e3e689a4283b27598d2' => $vendorDir . '/julien731/wp-dismissible-notices-handler/includes/helper-functions.php',
);
