name: CI Build
on: [push]

jobs:
  test:
    name: PHP Unit tests
    strategy:
      matrix:
        # php: [5.6,7.0,7.1,7.2,7.3]
        php: [7.3]
        node: [12.9.0]
        mysql: [5.7.27]
        # wordpress: [4.9.10,5.2.4,latest]
        wordpress: [latest]
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-apache
      env:
        NODE_ENV: production
      ports:
      - 80
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        volumes:
        - $HOME/mysql:/var/lib/mysql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up container
        # apt-get install -yq build-essential libssl-dev gnupg libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libicu-dev libxml2-dev vim wget unzip git subversion default-mysql-client nodejs
        run: |
          apt-get update
          apt-get install -yqq build-essential libssl-dev gnupg libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libicu-dev libxml2-dev vim wget unzip git subversion default-mysql-client
          docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring
          docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          docker-php-ext-install -j$(nproc) gd
          pecl install mcrypt-1.0.2
          docker-php-ext-enable mcrypt

      - name: Checkout Tools
        run: git clone https://${{ secrets.TOOLS_AUTOGIT_REPO_TOKEN }}@github.com/nextgenthemes/tools-autogit.git tools

      - name: Install composer with official install script
        run: |
          bash tools/install-composer
          mv composer.phar /usr/local/bin/composer

      # we do remove composer lock because we need different phpunit versions based on current PHP version
      - name: Run composer install
        run: |
          rm composer.lock
          composer install

      - name: Install WordPress Test Suite
        run: bash tools/install-wp-tests wordpress_test root root mysql ${{ matrix.wordpress }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit
  
  build:
    needs: test
    name: Build release Zip
    runs-on: ubuntu-latest
    #env:
      #ZIPFILE: ${{ $GITHUB_WORKSPACE }}/build/zip/${{ GITHUB_REPOSITORY }}-${{ $GITHUB_REF }}.zip
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

    #  - name: Dump GitHub context
    #     env:
    #       TTT: ${{ github.repository }}
    #     run: echo "$TTT"

    #   - name: Dump GitHub context
    #     env:
    #       TTT: ${{ github.REPOSITORY }}
    #     run: echo "$TTT"

  #     - name: Checkout repository
  #       uses: actions/checkout@v1

  #     - name: Checkout Tools
  #       run: git clone https://${{ secrets.TOOLS_AUTOGIT_REPO_TOKEN }}@github.com/nextgenthemes/tools-autogit.git tools

  #     - name: Set up container
  #       # apt-get install -yq build-essential libssl-dev gnupg libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libicu-dev libxml2-dev vim wget unzip git subversion default-mysql-client nodejs
  #       run: |
  #         apt-get update
  #         apt-get install -yqq default-mysql-client libssl-dev libmcrypt-dev wget unzip subversion
  #         bash tools/install-composer
  #         mv composer.phar /usr/local/bin/composer
  #         docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring
  #         # docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
  #         docker-php-ext-install -j$(nproc) gd

  #     - name: Build Zip
  #       run: bash tools/git-zip ${{ $ZIPFILE }}

  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: release Zip
  #         path: ${{ $ZIPFILE }}

  # deploy:
  #   on: tag
  #   needs: [test, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v1

  #     - name: Checkout Tools
  #       run: git clone https://${{ secrets.TOOLS_AUTOGIT_REPO_TOKEN }}@github.com/nextgenthemes/tools-autogit.git tools

  #     - name: Deploy
  #       run: bash tools/wporg-deploy