name: CI Build
on: [push, pull_request]

jobs:
  test:
    if: >-
      startsWith(github.ref, 'refs/tags')
      || contains(github.event.head_commit.message, '[ci]')
    name: PHP Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4' ]
        wordpress: [ '5.5.3', 'latest' ] # https://wordpress.org/download/releases/ 
        include:
          - php: '8.0'
            wordpress: 'latest'
          - php: '5.6'
            wordpress: '4.9.16' # Need to skip dailymotion in test_api_data
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: dbpass
          MYSQL_DATABASE: dbname
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout ARVE
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      - name: Checkout ARVE Pro
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
        with:
          repository: nextgenthemes/arve-pro
          ref: v5
          path: plugins/arve-pro
          token: ${{ secrets.REPO_TOKEN }}

      - name: Checkout ARVE Random Video
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
        with:
          repository: nextgenthemes/arve-random-video
          ref: master
          path: plugins/arve-random-video
          token: ${{ secrets.REPO_TOKEN }}

      - name: Checkout ARVE Random Video
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
        with:
          repository: nextgenthemes/arve-random-video
          ref: master
          path: plugins/arve-random-video
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@a83d4379b1200b3d0d19ad4fe0d7a440e00749c1 # 2.9.0 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, zip, mysql
          coverage: none #optional

      - name: Start mysql service
        run: sudo /etc/init.d/mysql start

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }} # Use composer.json if composer.lock is not committed.
          restore-keys: ${{ runner.os }}-composer-

      - name: Remove composer.lock # this does not work as different packages for different php versions are needed
        run: rm composer.lock

      - if: matrix.php == '8.0'
        name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --ignore-platform-req=php
      - if: matrix.php != '8.0'
        name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader    

      - name: Install WP Tests
        run: bash ./bin/install-wp-tests.sh dbname root dbpass "127.0.0.1:$DB_PORT" ${{ matrix.wordpress }} true
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Run PHPUnit without code coverage
        run: vendor/bin/phpunit

  wporgrelease:
    if: >-
      startsWith(github.ref, 'refs/tags')
      && ! startsWith(github.event.repository.name, 'arve-')
      && ! contains(github.ref, 'alpha')
    needs: test
    name: SVN commit to wp.org
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_REF#refs/tags/-- ${GITHUB_REF#refs/tags/}"
      - run: echo "github.event.repository.name-- ${{ github.event.repository.name }}"
      - run: echo "github.ref-- ${{ github.ref }}"

      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      # - name: Setup PHP, with composer and extensions
      #   uses: shivammathur/setup-php@a83d4379b1200b3d0d19ad4fe0d7a440e00749c1 # 2.9.0 # https://github.com/shivammathur/setup-php
      #   with:
      #     php-version: '5.6'
      #     extensions: mbstring, dom
      #     coverage: none

      # - name: Install Composer dependencies
      #   run: composer install --no-dev --no-progress --no-suggest --prefer-dist --optimize-autoloader
      #   with:
      #     working-directory: advanced-responsive-video-embedder

      - name: Maybe deploy to wp.org
        uses: 10up/action-wordpress-plugin-deploy@0dc3f76f710b55cd07aa546a77bc103a0f1f2f7a # 1.5.0 https://github.com/10up/action-wordpress-plugin-deploy/tags
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        with:
          working-directory: plugins/advanced-responsive-video-embedder
          create zip: false
