name: CI Build
on: [push]

jobs:
  test:
    name: PHP Unit tests
    strategy:
      matrix:
        php: [5.6,7.1,7.2,7.3] # There is NO 7.0 docker image, it will be displayed as '7' and will actually be the latest 7.x
        mysql: [5.7.27]
        wordpress: [4.9.12,5.0.7,5.1.3,5.2.4,latest]
        exclude: # WP Bug https://core.trac.wordpress.org/ticket/44416
          - php: 7.3
            mysql: 5.7.27
            wordpress: 4.9.12
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-apache
      ports:
        - 80
      volumes:
        - $GITHUB_WORKSPACE:/var/www/html
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        volumes:
          - $HOME/mysql:/var/lib/mysql
    steps:
      - uses: actions/checkout@v1

      - name: APT + docker
         # https://bigbite.net/insights/github-actions-ci-cd-with-yarn-composer-phpcs-phpunit-and-built-branches/ reminder
        run: |
          apt-get update -yqq
          apt-get install -yqqf default-mysql-client vim wget zip unzip git subversion libmcrypt-dev --fix-missing
          docker-php-ext-install mysqli pdo_mysql mbstring pcntl

      - name: Install composer
        run: bash bin/install-composer.sh
      
      - name: Run composer install
        run: |
          rm composer.lock # we do remove composer lock because we need different phpunit versions based on current PHP version
          composer install --quiet --no-interaction

      - name: Install WordPress Test Suite
        run: bash bin/install-wp-tests.sh wordpress_test root root mysql ${{ matrix.wordpress }}

      - name: Run PHPUnit without code coverage
        #if: matrix.wordpress != 'latest' && matrix.php != '7.3'
        run: vendor/bin/phpunit

      # - name: Install xdebug, Coveralls, run PHPunit with coverage analysis
      #   if: matrix.wordpress == 'latest' && matrix.php == '7.3'
      #   run: |
      #     pecl install xdebug # fails for php 5.6
      #     docker-php-ext-enable xdebug
      #     composer require --dev php-coveralls/php-coveralls 
      #     vendor/bin/phpunit --coverage-text --colors=never

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - env:
          DEBUG: ${{ github.ref }}
        run: echo "$DEBUG"

      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.event.repository.name }}"

      - if: startsWith(github.ref, 'refs/tags') && ! contains(github.ref, 'beta') && ! contains(github.ref, 'alpha')
        name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: advanced-responsive-video-embedder
