name: readme-update
on:
  push:
    branches:
      - master

jobs:
  update-readme:
    if: contains(github.event.head_commit.message, '[readme]')
    name: Readme and Asset update to wp.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: advanced-responsive-video-embedder

      - run: pwd

      - name: Deploy
        uses: nextgenthemes/action-wordpress-plugin-deploy@master
        with:
          workdir: advanced-responsive-video-embedder
          svn_user: ${{ secrets.SVN_USERNAME }}
          svn_pass: ${{ secrets.SVN_PASSWORD }}
          readme-and-assets-only: true
          verbose: true


