name: CI Build
on:
  push:
    branches: 
      - master

jobs:
  update-readme:
    name: SVN commit to wp.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      - name: Deploy
        uses: ./actions/wp-plugin-deploy
        with:
          args: --workdir=plugins/advanced-responsive-video-embedder --svn-user='${{ secrets.SVN_USERNAME }}' --svn-pass='${{ secrets.SVN_PASSWORD }}' --readme-only --dry-run
