name: test-deploy
on: [push, pull_request]

jobs:
  test:
    if: >-
      startsWith(github.ref, 'refs/tags')
      || contains(github.event.head_commit.message, '[ci]')
    name: PHP Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4' ]
        wordpress: [ '5.7.3', 'latest' ] # https://wordpress.org/download/releases/ 
        include:
          - php: '5.6'
            wordpress: '4.9.16' # Need to skip dailymotion in test_api_data
          - php: '8.0'
            wordpress: 'latest'
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: dbpass
          MYSQL_DATABASE: dbname
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout ARVE
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      - name: Checkout ARVE Pro
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
        with:
          repository: nextgenthemes/arve-pro
          ref: v5
          path: plugins/arve-pro
          token: ${{ secrets.REPO_TOKEN }}

      - name: Checkout ARVE Random Video
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
        with:
          repository: nextgenthemes/arve-random-video
          ref: master
          path: plugins/arve-random-video
          token: ${{ secrets.REPO_TOKEN }}

      - name: Checkout ARVE AMP
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
        with:
          repository: nextgenthemes/arve-amp
          ref: master
          path: plugins/arve-amp
          token: ${{ secrets.REPO_TOKEN }}

      # - name: Checkout ARVE Sticky Videos
      #   uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
      #   with:
      #     repository: nextgenthemes/arve-sticky-videos
      #     ref: master
      #     path: plugins/arve-sticky-videos
      #     token: ${{ secrets.REPO_TOKEN }}

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@abfbe6a46b637e038be212af3c5d3475b3e3213c # 2.10.0 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, zip, mysql, gd
          coverage: none #optional

      - name: Start mysql service
        run: sudo /etc/init.d/mysql start

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }} # Use composer.json if composer.lock is not committed.
          restore-keys: ${{ runner.os }}-composer-

      - name: Remove composer.lock # this does not work as different packages for different php versions are needed
        run: rm composer.lock

      - if: matrix.php == '8.0'
        name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --ignore-platform-req=php
      - if: matrix.php != '8.0'
        name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader    

      - name: Install WP Tests
        run: bash ./bin/install-wp-tests.sh dbname root dbpass "127.0.0.1:$DB_PORT" ${{ matrix.wordpress }} true
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Run PHPUnit without code coverage
        run: vendor/bin/phpunit

  deploy:
    if: >-
      startsWith(github.ref, 'refs/tags')
      && ! startsWith(github.event.repository.name, 'arve-')
      && ! contains(github.ref, 'alpha')
    needs: test
    name: SVN commit to wp.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      # - name: Install Composer dependencies
      #   run: composer install --no-dev --no-progress --no-suggest --prefer-dist --optimize-autoloader
      #   with:
      #     working-directory: plugins/advanced-responsive-video-embedder

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Deploy
        uses: ./actions/wp-plugin-deploy
        with:
          workdir: plugins/advanced-responsive-video-embedder
          version: ${{ steps.get_version.outputs.VERSION }}
          svn_user: ${{ secrets.SVN_USERNAME }}
          svn_pass: ${{ secrets.SVN_PASSWORD }}
